#!/usr/bin/env bash
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OSMO_SOURCE_DIR="${OSMO_SOURCE_DIR:-${PROJECT_ROOT}/third_party/osmo-tetra}"
OSMO_TOOL_DIR="${OSMO_TOOL_DIR:-${PROJECT_ROOT}/tools/osmocom-tetra/bin}"

log() {
    printf '[osmocom-tetra] %s\n' "$*"
}

die() {
    printf '[osmocom-tetra] Fehler: %s\n' "$*" >&2
    exit 1
}

ensure_submodule() {
    if [[ -f "${OSMO_SOURCE_DIR}/src/Makefile" ]]; then
        return
    fi

    if [[ ! -d "${PROJECT_ROOT}/.git" ]]; then
        die "Submodule fehlt und ${PROJECT_ROOT} ist kein Git-Checkout."
    fi

    log "Initialisiere third_party/osmo-tetra..."
    git -C "${PROJECT_ROOT}" submodule update --init --recursive third_party/osmo-tetra
}

check_build_requirements() {
    command -v make >/dev/null 2>&1 || die "make fehlt."
    command -v pkg-config >/dev/null 2>&1 || die "pkg-config fehlt."
    pkg-config --exists libosmocore || die "libosmocore-dev fehlt."
}

build_and_install() {
    log "Baue offizielle Osmocom-TETRA Werkzeuge aus ${OSMO_SOURCE_DIR}..."
    make -C "${OSMO_SOURCE_DIR}/src"

    mkdir -p "${OSMO_TOOL_DIR}"
    install -m 0755 "${OSMO_SOURCE_DIR}/src/tetra-rx" "${OSMO_TOOL_DIR}/tetra-rx"
    install -m 0755 "${OSMO_SOURCE_DIR}/src/float_to_bits" "${OSMO_TOOL_DIR}/float_to_bits"

    cat > "${OSMO_TOOL_DIR}/README.txt" <<'EOF'
Generated by scripts/ensure_osmocom_tetra.sh.

These binaries are built from third_party/osmo-tetra and are intentionally
ignored by git. Re-run the script after updating the submodule.
EOF
}

warn_optional_runtime() {
    if ! command -v python3 >/dev/null 2>&1; then
        log "Warnung: python3 fehlt; simdemod3.py kann nicht gestartet werden."
        return
    fi
    if ! python3 -c 'import gnuradio' >/dev/null 2>&1; then
        log "Warnung: GNU Radio Python-Modul fehlt; installiere gnuradio fuer Live-Demodulation."
    fi
}

ensure_submodule
check_build_requirements
build_and_install
warn_optional_runtime

log "Fertig. Toolpfad: ${OSMO_TOOL_DIR}"
